services:
    # Event Subscriber
    akeneo_frontoffice.form.event_subscriber.event_to_api:
        class: Akeneo\Bundle\FrontofficeBundle\Form\EventSubscriber\EventToApiSubscriber
        arguments:
            - @security.token_storage

    akeneo_frontoffice.form.event_subscriber.subscriber_to_api:
        class: Akeneo\Bundle\FrontofficeBundle\Form\EventSubscriber\SubscriberToApiSubscriber
        arguments:
            - @security.token_storage

    # Types
    akeneo_frontoffice.form.type.event:
        class: Akeneo\Bundle\FrontofficeBundle\Form\Type\EventType
        arguments:
            - @akeneo_frontoffice.form.event_subscriber.event_to_api
            - %event_tags%
        tags:
            - { name: form.type, alias: frontoffice_event }

    akeneo_frontoffice.form.type.subscriber:
        class: Akeneo\Bundle\FrontofficeBundle\Form\Type\SubscriberType
        arguments:
            - @akeneo_frontoffice.form.event_subscriber.subscriber_to_api
        tags:
            - { name: form.type, alias: frontoffice_subscriber }
