language: php
php:
  - 5.5
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - composer install --prefer-dist --optimize-autoloader

script:
  - bin/phpspec run --format=pretty