akeneo_frontoffice:
    resource: Akeneo\Bundle\FrontofficeBundle\Controller\HomePageController
    type:     annotation
    prefix:   /

akeneo_api_event:
    resource: akeneo_api.controller.event
    type:     rest
    prefix:   /api/
