akeneo_frontoffice:
    resource: Akeneo\Bundle\FrontofficeBundle\Controller\DefaultController
    type:     annotation
    prefix:   /

akeneo_api_event:
    resource: Akeneo\Bundle\ApiBundle\Controller\EventController
    type:     rest
    prefix:   /api/
