akeneo_frontoffice:
    resource: "@AkeneoFrontofficeBundle/Resources/config/routing.xml"
    type:     rest
    prefix:   /

akeneo_api:
    resource: "@AkeneoApiBundle/Resources/config/routing.xml"
    type:     annotation
    prefix:   /api/
